name: Daily Update

on:
  schedule:
    - cron: '0 12 * * *'  # Run daily at 12:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_and_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Run update script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python main.py

      - name: Check for updates and commit
        if: env.UPDATES_FOUND == 'true'
        uses: IAreKyleW00t/verified-bot-commit@v1
        with:
          message: "Updated ${{ env.UPDATED_CATEGORIES }}"
          files: |
            **
          if-no-commit: info

      - name: No updates found
        if: env.UPDATES_FOUND == 'false'
        run: echo "No updates found, skipping commit"
