name: Daily Update

on:
  schedule:
    - cron: '0 12 * * *'  # Run daily at 12:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_and_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Run update script
        run: python main.py

      - name: Check for updates and commit
        if: env.UPDATES_FOUND == 'true'
        run: |
          COMMIT_MESSAGE="Updated ${{ env.UPDATED_CATEGORIES }}"
          
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "${COMMIT_MESSAGE}"
          git push

      - name: No updates found
        if: env.UPDATES_FOUND == 'false'
        run: echo "No updates found, skipping commit"